In [10]:
import pandas as pd
import numpy as np
import sqlite3

In [11]:
data = pd.read_csv("raw_analyst_ratings_data.csv")

In [12]:
data.head()

,Unnamed: 0,headline,url,publisher,date,stock
0,21991,"UBS Maintains Buy on Adobe, Raises Price Targe...",https://www.benzinga.com/news/20/06/16202690/u...,Benzinga Newsdesk,2020-06-08 10:57:41-04:00,ADBE
1,21992,Stocks That Hit 52-Week Highs On Thursday,https://www.benzinga.com/news/20/06/16180865/s...,Benzinga Insights,2020-06-04 10:48:11-04:00,ADBE
2,21993,Shares of several companies in the broader tec...,https://www.benzinga.com/wiim/20/05/16116988/s...,Benzinga Newsdesk,2020-05-27 10:24:38-04:00,ADBE
3,21994,Stocks That Hit 52-Week Highs On Tuesday,https://www.benzinga.com/news/20/05/16106805/s...,Benzinga Insights,2020-05-26 10:32:14-04:00,ADBE
4,21995,Shares of several technology companies are tra...,https://www.benzinga.com/wiim/20/05/16075931/s...,Benzinga Newsdesk,2020-05-20 10:19:31-04:00,ADBE

In [13]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 107805 entries, 0 to 107804
Data columns (total 6 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   Unnamed: 0  107805 non-null  int64
 1   headline    107805 non-null  object
 2   url         107805 non-null  object
 3   publisher   107805 non-null  object
 4   date        107805 non-null  object
 5   stock       107805 non-null  object
dtypes: int64(1), object(5)
memory usage: 4.9+ MB

In [14]:
data.describe()

         Unnamed: 0
count  1.078050e+05
mean   6.428957e+05
std    3.850003e+05
min    2.199100e+04
25%    2.651510e+05
50%    7.094280e+05
75%    8.972850e+05
max    1.411295e+06

In [15]:
data.isnull()

        Unnamed: 0  headline    url  publisher   date  stock
0            False     False  False      False  False  False
1            False     False  False      False  False  False
2            False     False  False      False  False  False
3            False     False  False      False  False  False
4            False     False  False      False  False  False
...            ...       ...    ...        ...    ...    ...
107800       False     False  False      False  False  False
107801       False     False  False      False  False  False
107802       False     False  False      False  False  False
107803       False     False  False      False  False  False
107804       False     False  False      False  False  False

[107805 rows x 6 columns]

In [ ]:
con = sqlite3.connect("ratings.db")
cur = con.cursor()
cur.execute("""
            CREATE TABLE IF NOT EXISTS articles(
            article_id INTEGER PRIMARY KEY,
            headline TEXT NOT NULL,
            url TEXT,
            publisher TEXT,
            published_at TEXT NOT NULL,
            ticker TEXT NOT NULL)
            """)

cur.execute("""
            CREATE TABLE IF NOT EXISTS returns(
            article_id INTEGER PRIMARY KEY,
            return_7d REAL,
            return_30d REAL,
            return_6m0 REAL,
            price TEXT,
            FOREIGN KEY(article_id) REFERENCES articles(article_id))
            """)

cur.execute("""
            CREATE TABLE IF NOT EXISTS sentiment(
            article_id INTEGER PRIMARY KEY,
            sentiment_score REAL,
            sentiment_label REAL,
            method TEXT,
            FOREIGN KEY(article_id) REFERENCES articles(article_id))
            """)