In [5]:

"""
On 2/5/2026 we went over the current state of the project and we talked about what the actual goal is. My data
contains rows consisting of the headline of the article, the publisher, the date it was published, and the stock ticker. 
The goal for this project is to investigate the stocks performance after the article published date and compare results
to the sentiment behind the headline to classify the publisher has good, bad, etc. After we spoke we decided it would be beneficial
to add a column that semi accurately classifies the headlines as a prediction, movement, or just general news because we noted how
a vast majority of articles in this dataset tend to be just objective "on this date the price was x" which may need to be filtered out for
actual training because this has no weighting on how good the publisher is unless they are objetively lying about the stock price but thats a very very small edge case.

The goal for this file is to create a categories column that sorts the headline into opinion, price movement, forward looking and general news.
This may be subject to change but all im doing is checking for keywords in the headline string and categorizing if the string contains the keyword.

"""

'\nOn 2/5/2026 we went over the current state of the project and we talked about what the actual goal is. My data\ncontains rows consisting of the headline of the article, the publisher, the date it was published, and the stock ticker. \nThe goal for this project is to investigate the stocks performance after the article published date and compare results\nto the sentiment behind the headline to classify the publisher has good, bad, etc. After we spoke we decided it would be beneficial\nto add a column that semi accurately classifies the headlines as a prediction, movement, or just general news because we noted how\na vast majority of articles in this dataset tend to be just objective "on this date the price was x" which may need to be filtered out for\nactual training because this has no weighting on how good the publisher is unless they are objetively lying about the stock price but thats a very very small edge case.\n\nThe goal for this file is to create a categories column that sorts the headline into opinion, price movement, forward looking and general news.\nThis may be subject to change but all im doing is checking for keywords in the headline string and categorizing if the string contains the keyword.\n\n'

In [4]:
import pandas as pd
import numpy as np
import sqlite3
data = pd.read_csv("raw_analyst_ratings_data.csv")

In [3]:
data.head()

,Unnamed: 0,headline,url,publisher,date,stock
0,21991,"UBS Maintains Buy on Adobe, Raises Price Targe...",https://www.benzinga.com/news/20/06/16202690/u...,Benzinga Newsdesk,2020-06-08 10:57:41-04:00,ADBE
1,21992,Stocks That Hit 52-Week Highs On Thursday,https://www.benzinga.com/news/20/06/16180865/s...,Benzinga Insights,2020-06-04 10:48:11-04:00,ADBE
2,21993,Shares of several companies in the broader tec...,https://www.benzinga.com/wiim/20/05/16116988/s...,Benzinga Newsdesk,2020-05-27 10:24:38-04:00,ADBE
3,21994,Stocks That Hit 52-Week Highs On Tuesday,https://www.benzinga.com/news/20/05/16106805/s...,Benzinga Insights,2020-05-26 10:32:14-04:00,ADBE
4,21995,Shares of several technology companies are tra...,https://www.benzinga.com/wiim/20/05/16075931/s...,Benzinga Newsdesk,2020-05-20 10:19:31-04:00,ADBE

In [7]:
Analysis = [
    "upgrade", "upgraded", "upgrades", "downgrade", "downgraded", "downgrades",
    "initiates", "initiated", "rating", "ratings", "rated", "price target",
    "raises target", "cuts target", "pt", "buy", "sell", "hold"
]

Movement = [
    "shares", "stock", "up", "down", "rises", "falls",
    "gains", "drops", "surges", "plunges", "climbs",
    "tumbles", "slips", "higher", "lower", "plunge", "plunged",
    "fell", "falling", "slip", "slipped", "tumble", "rise'"
]

Prediction = [
    "expects", "expected", "forecast", "outlook",
    "guidance", "projects", "projected", "could",
    "may", "might", "likely", "unlikely", "project", "predict",
    "could"
]

In [8]:
def classifyHeadline(headline):
    if pd.isna(headline):
        return "No Headline"

    myHeadline = str(headline).lower()

    for word in Analysis:
        if word in myHeadline:
            return "Analysis"

    for word in Movement:
        if word in myHeadline:
            return "Movement"

    for word in Prediction:
        if word in myHeadline:
            return "Prediction"
        
    return "General"

In [10]:
data["Headline Class"] = data["headline"].apply(classifyHeadline)

print(data["Headline Class"].value_counts())

Headline Class
General       48544
Movement      28957
Analysis      25965
Prediction     4339
Name: count, dtype: int64

In [12]:
data.groupby("Headline Class").head(5)[
    ["Headline Class", "headline"]
]

    Headline Class                                           headline
0         Analysis  UBS Maintains Buy on Adobe, Raises Price Targe...
1         Movement          Stocks That Hit 52-Week Highs On Thursday
2         Movement  Shares of several companies in the broader tec...
3         Movement           Stocks That Hit 52-Week Highs On Tuesday
4         Analysis  Shares of several technology companies are tra...
5         Analysis  Benzinga's Top Upgrades, Downgrades For May 14...
6         Analysis  DZ Bank Downgrades Adobe to Hold, Announces $3...
7         Movement  Shares of several technology companies are tra...
8          General  'Fast Money' Traders Answer Questions On Uber,...
9         Analysis  BMO Capital Maintains Outperform on Adobe, Rai...
10        Movement  Shares of several technology companies are tra...
14         General  The Show Must Go On – Event Industry Rising To...
15         General  Adobe Co-Founder Dr. Charles M. Geschke To Ret...
34         General                     144 Biggest Movers From Friday
36      Prediction  Adobe Beats Q1 Targets, But Expects A Coronavi...
50         General  Adobe Sees Q2 Adj. EPS ~$2.35 vs $2.33 Estimat...
61      Prediction  Just Like With Any Champion, Steady Growth And...
160     Prediction  Adobe Raises Q4 Digital Media Net New Annualiz...
217     Prediction  Canaccord Genuity Analyst Richard Davis Commen...
383     Prediction             Adobe Reaffirms Q4 Sales, EPS Guidance

In [13]:
data.to_csv("raw_data_classified_headlines.csv")